### PR TITLE
LPS-77010 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test

**Comment by marcellustavares** [comment]
ci:test

**Comment by marcellustavares** [comment]
@vicnate5, could you please give me a hand on this? I'm not sure why CI is not responding.

Thanks

**Comment by vicnate5** [comment]
@marcellustavares The CI does not handle the "release" branch. Could you send this pull to `liferay:master`?

**Comment by marcellustavares** [comment]
got it, thx @vicnate5, it's already merged in master.

**Pull request merged**
