### PR TITLE
LPS-75418 Fix jackson annotations

### PR DESCRIPTION
**Pull request by marcellustavares**
This is related to https://github.com/liferay/com-liferay-analytics/pull/15

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by lesliewong92** [comment]
ci:retest

**Comment by epgarcia** [comment]
@marcellustavares Waiting for #15 to be approved before merging this one.

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Pull request submitted to https://github.com/liferay/com-liferay-analytics/pull/20. [See changes here.](https://github.com/liferay/com-liferay-analytics/compare/09dd20d~2...09dd20d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
