### PR TITLE
LPS-75418 Update tests to the new message format.

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
@epgarcia, I've submitted a proposal to https://github.com/liferay/com-liferay-analytics/pull/21

**Comment by marcellustavares** [comment]
ci:close

**Pull request closed without merging**
