### PR TITLE
LPS-75890

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/com-liferay-analytics/pull/6

**Comment by epgarcia** [comment]
@jbalsas @vbence86 Could you please readd and check format of **all** the comments in the JS files, following @brianchandotcom 's example in brianchandotcom#4? Thanks!

**Comment by vbence86** [comment]
@brianchandotcom @epgarcia For what's worth, I kindly suggest that GitHub's **Change Request** facility should be employed to individually highlight all the required changes so that we could avoid similar situations from occurring in the future.

**Comment by jbalsas** [comment]
I'm closing this. I'll work this out and overlay it with https://github.com/liferay/com-liferay-analytics/pull/34

**Comment by jbalsas** [comment]
ci:close

**Pull request closed without merging**
