### PR TITLE
LPS-75200 Add analytics message bus destination

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by lesliewong92** [comment]
ci:retest

**Comment by epgarcia** [comment]
Hi @marcellustavares and @riccardo-ferrari

The goal of these changes is to send the server-side analytics in Liferay through the message bus and the java client, right? I think we have some overlapping with https://github.com/liferay/com-liferay-lcs-private/blob/7.0.x-private/lcs-messaging/src/main/java/com/liferay/lcs/messaging/LCSMessageBusService.java and https://github.com/liferay/com-liferay-lcs-private/blob/7.0.x-private/lcs-messaging/src/main/java/com/liferay/lcs/messaging/analytics/AnalyticsEventsMessage.java.

@riccardo-ferrari added a service to send messages to LCS via Liferay's message bus. You just need to know the destination in LCS (e.g. analytics) and it does everything else. And a definition of the AnalyticsEventMessage is even provided.

@marcellustavares I think it is a good idea to use the same generic non-Liferay-specific analytics client everywhere (including Liferay) but we should coordinate this with @riccardo-ferrari and agree an strategy for this and other similar cases (like the contacts connector in Liferay and other platforms for Single Customer View, for instance).

@riccardo-ferrari I'll wait for your response before I merge this PR. 

Thanks you all!

CC @juliocamarero

**Comment by riccardo-ferrari** [comment]
@epgarcia thanks for pointing this out!

Indeed for SCV and CM we developed a bundle (lcs-messaging you linked) to make sending data from a DE servers super easy.

I think the most important things about the lcs-messaging library are:
- No new firewall exceptions required (!) on the customer side as it leverages on the lcs-portlet
- Leverages on existing lcs-portlet code and connection, enabling features like message compression
- just wrap you payload into a MessageBusMessage and send it to a well-known (LCS) destination

During the analysis done for SCV and CM the first point was critical.

Is there anything that speaks against using the lcs-messaging library?

I'd like to hear @juliocamarero and of course @ivicac ideas about this too.

Thanks!

**Comment by marcellustavares** [comment]
Hey guys,

The rationale behind this module, which is Liferay portal deploy specific, is to act as a endpoint for all portal apps messages being sent to the cloud. Currently it registers an message bus destination to be used by portal backend apps, such as workflow. Later on we might need to have a servlet to also act as endpoint for the js events.

The benefits would be:

1. Better control of messages being sent to the cloud, so we can optimize IO later on.
2. Ability to discard analytics events messages if the customer is not subscribed to the cloud services, etc.

I'm not familiar with the lcs-messaging nor lcs-portlet but it might be the case here and we might be overlapping features.

**Comment by riccardo-ferrari** [comment]
Hey @marcellustavares, 

So based on your comment I believe lcs-portlet along with its lcs-messaging module does already what you're looking for.
Personally I don't mind or better I like the idea of having a unique and privileged connection system between liferay instances and the "cloud" (read LCS) and that is the lcs-portlet.

I am open for a call altogether to better dig into this if required.

**Comment by ivicac** [comment]
Hi @marcellustavares,
the general strategy is to use lcs-portlet and LCSMessageBusService for all modules in DE instances that want to communicate with the cloud for all reasons @riccardo-ferrari described.

I know that complicates things, but as far as I remember while we were prototyping osb-lcs-analytics-gateway for Audience Targeting, its primary role should be to accept analytics events coming directly from the browser, native mobile apps, or third party systems(in general non-Liferay environments).

Best Regards

**Comment by juliocamarero** [comment]
Hey guys, let's talk about this in our call later today 👍

**Comment by epgarcia** [comment]
Hey @marcellustavares and @riccardo-ferrari 

What's the status of this PR? Should I close it or merge it? 

Thanks!

**Comment by epgarcia** [comment]
Closing. We'll need to use LCS infrastructure in the AnalyticsClient implementation for Liferay. This requires separating the LCS messaging logic from the LCS portlet.

**Pull request closed without merging**
