### PR TITLE
LPS-79146 Adds regression test

### PR DESCRIPTION
**Pull request by brunobasto**
/cc @marcellustavares

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test

**Comment by brunobasto** [comment]
ci:test

**Comment by brunobasto** [comment]
ci:test

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
resent to https://github.com/liferay/com-liferay-analytics/pull/65

**Pull request closed without merging**
