### PR TITLE
Android and iOS clients

### PR DESCRIPTION
**Pull request by igormatos**

### CODE REVIEW

**Comment by igormatos** [comment]
ci:test

**Comment by igormatos** [comment]
ci:test

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
As discussed with @epgarcia @nhpatt and @allanragec over a call, we opted to move mobile clients code to a liferay-mobile organization.

**Reasons**: better flexibility (code standards, testing pattern,  release, etc) and greater autonomy to the mobile team.

Even with code separated in different repos, we still have the need need in alignment regarding major releases and documentation.

**Comment by marcellustavares** [comment]
As a side note we might eventually link the mobile repos to this repo using submodules.

**Pull request closed without merging**
