### PR TITLE
LPS-75174 Fix compilation error

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Merging this to make the repository compile again, this pull request broke it: https://github.com/brianchandotcom/com-liferay-analytics/pull/2

 cc @brianchandotcom @marcellustavares

**Comment by marcellustavares** [comment]
hey @juliocamarero, my bad :( I thought it was safe to push change fwd to speed things up but it wasn't.

**Comment by marcellustavares** [comment]
thanks @epgarcia!

**Pull request merged**
